import { Input, CheckBox, DatePicker } from '@ui5/webcomponents-react'
import { formatCellValue, formatDateForSap } from '../utils/displayHelpers'
import { isAutoGeneratedKeyField, isFieldReadonly, isSystemGeneratedField } from '../utils/recordHelpers'
import DomainValueHelp from './DomainValueHelp'
import FkValueHelp from './FkValueHelp'
import { FieldMeta, TableRowData } from '../types'

interface CellEditControlProps {
  row: TableRowData
  rowIndex: number
  field: FieldMeta
  inlineErrors: Record<number, Record<string, string>>
  configUuid: string
  tableName: string
  onCellChange: (rowIndex: number, fieldName: string, newValue: any) => void
}

/**
 * ===================================================================================
 * 🧩 DYNAMIC METADATA ENGINE & INLINE EDIT CONTROL (SINH LINH KIỆN NHẬP LIỆU ĐỘNG)
 * ===================================================================================
 * Component này nhận vào thuộc tính 'fe_type' của trường dữ liệu (được phân tích từ
 * module fieldMeta.ts) và tự động quyết định sinh ra Control UI tương ứng:
 * 
 *  1. feType === 'date'      => Render UI5 <DatePicker /> (Định dạng YYYY-MM-DD)
 *  2. feType === 'boolean'   => Render UI5 <CheckBox /> (Giá trị 'X' hoặc '')
 *  3. feType === 'domain'    => Render Hộp thoại Value Help chọn giá trị cố định Domain
 *  4. feType === 'fk_select' => Render Hộp thoại Search Help chọn Khóa ngoại Parent
 *  5. Mặc định               => Render UI5 <Input /> kèm Real-time Validation Error
 * ===================================================================================
 */
export default function CellEditControl({
  row,
  rowIndex,
  field: f,
  inlineErrors,
  configUuid,
  tableName,
  onCellChange,
}: CellEditControlProps) {
  const name = f.field_name || f.FieldName
  const val = row[name] ?? ''
  const isNewRow = !!row._isNew
  const mode = isNewRow ? 'create' : 'edit'

  // Kiếm tra trường bị Read-Only hoặc Khóa chính tự động sinh khi Sửa dòng
  const readonly =
    isFieldReadonly(f, mode) ||
    isSystemGeneratedField(f) ||
    (mode === 'edit' && (f.is_key || f.IsKeyField === 'X'))

  if (readonly) {
    return (
      <span style={{ color: '#6a7075', fontSize: '0.875rem' }}>
        {isAutoGeneratedKeyField(f, mode) ? 'Generated automatically' : formatCellValue(f, val)}
      </span>
    )
  }

  const feType = f.fe_type || f.FeType
  // Lấy câu cảnh báo lỗi Validation thời gian thực của ô hiện tại
  const cellError = inlineErrors[rowIndex]?.[name]

  // [ĐỘNG 1] Render Ô Ngày tháng (Date)
  if (feType === 'date') {
    const dateValue = val ? String(val).substring(0, 10) : ''
    return (
      <DatePicker
        className="table-date-picker"
        formatPattern="yyyy-MM-dd"
        value={dateValue}
        onChange={(e: any) => onCellChange(rowIndex, name, formatDateForSap(e.target.value))}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [ĐỘNG 2] Render Ô Boolean (Checkbox 'X' / '')
  if (feType === 'boolean') {
    const isChecked = val === 'X' || val === true
    return (
      <CheckBox
        checked={isChecked}
        onChange={(e: any) => onCellChange(rowIndex, name, e.target.checked ? 'X' : '')}
      />
    )
  }

  // [ĐỘNG 3] Render Hộp thoại Value Help cho Domain fixed values
  if (feType === 'domain') {
    return (
      <DomainValueHelp
        configUuid={configUuid}
        field={f}
        value={val}
        onChange={newVal => onCellChange(rowIndex, name, newVal)}
        readonly={false}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [ĐỘNG 4] Render Hộp thoại Search Help cho Khóa ngoại (Parent Foreign Key)
  if (feType === 'fk_select') {
    return (
      <FkValueHelp
        configUuid={configUuid}
        tableName={tableName}
        field={f}
        value={val}
        onChange={newVal => onCellChange(rowIndex, name, newVal)}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [ĐỘNG 5] Render Ô nhập liệu Văn bản / Số mặc định kèm Cảnh báo Lỗi Validation
  return (
    <Input
      value={val}
      onInput={(e: any) => onCellChange(rowIndex, name, e.target.value)}
      style={{ width: '100%' }}
      valueState={cellError ? 'Negative' : 'None'}
      valueStateMessage={
        cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
      }
    />
  )
}
