import { Input, CheckBox, DatePicker } from '@ui5/webcomponents-react'
import { formatCellValue, formatDateForSap } from '../utils/displayHelpers'
import { isAutoGeneratedKeyField, isFieldReadonly, isSystemGeneratedField } from '../utils/recordHelpers'
import DomainValueHelp from './DomainValueHelp'
import { FieldMeta, TableRowData } from '../types'

interface CellEditControlProps {
  row: TableRowData
  rowIndex: number
  field: FieldMeta
  inlineErrors: Record<number, Record<string, string>>
  configUuid: string
  onCellChange: (rowIndex: number, fieldName: string, newValue: any) => void
}

/**
 * Renders the appropriate edit control for a single table cell
 * based on the field's fe_type (date, boolean, domain, text).
 * Falls back to a read-only Text display for key/system-generated fields.
 */
export default function CellEditControl({
  row,
  rowIndex,
  field: f,
  inlineErrors,
  configUuid,
  onCellChange,
}: CellEditControlProps) {
  const name = f.field_name || f.FieldName
  const val = row[name] ?? ''
  const isNewRow = !!row._isNew
  const mode = isNewRow ? 'create' : 'edit'

  const readonly =
    isFieldReadonly(f, mode) ||
    isSystemGeneratedField(f) ||
    (mode === 'edit' && (f.is_key || f.IsKeyField === 'X'))

  if (readonly) {
    return (
      <span style={{ color: '#6a7075', fontSize: '0.875rem' }}>
        {isAutoGeneratedKeyField(f, mode) ? 'Generated automatically' : formatCellValue(f, val)}
      </span>
    )
  }

  const feType = f.fe_type || f.FeType
  const cellError = inlineErrors[rowIndex]?.[name]

  if (feType === 'date') {
    const dateValue = val ? String(val).substring(0, 10) : ''
    return (
      <DatePicker
        className="table-date-picker"
        formatPattern="yyyy-MM-dd"
        value={dateValue}
        onChange={(e: any) => onCellChange(rowIndex, name, formatDateForSap(e.target.value))}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  if (feType === 'boolean') {
    const isChecked = val === 'X' || val === true
    return (
      <CheckBox
        checked={isChecked}
        onChange={(e: any) => onCellChange(rowIndex, name, e.target.checked ? 'X' : '')}
      />
    )
  }

  if (feType === 'domain') {
    return (
      <DomainValueHelp
        configUuid={configUuid}
        field={f}
        value={val}
        onChange={newVal => onCellChange(rowIndex, name, newVal)}
        readonly={false}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  return (
    <Input
      value={val}
      onInput={(e: any) => onCellChange(rowIndex, name, e.target.value)}
      style={{ width: '100%' }}
      valueState={cellError ? 'Negative' : 'None'}
      valueStateMessage={
        cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
      }
    />
  )
}
