/**
 * ============================================================================
 * FILE: src/components/CellEditControl.tsx
 * ----------------------------------------------------------------------------
 * VAI TRO: Bo sinh linh kien nhap lieu dong tren tung o Cell (Dynamic Input Engine).
 * ----------------------------------------------------------------------------
 * CAC NHIEM VU CHINH:
 *   - 1. Nhan vao metadata f.fe_type tu fieldMeta.ts va tu dong quyet dinh sinh Control UI5 tuong ung.
 *   - 2. Khoa disabled cac truong Khoa chinh (Primary Key) khi o che do Edit de bao ve toan ven du lieu.
 *   - 3. Hien thi o DatePicker, CheckBox, Dropdown DomainValueHelp, Dialog FkValueHelp, hoac Input.
 *   - 4. Gan trang thai loi ValueState = 'Negative' va hien thi message loi thoi gian thuc khi validation that bai.
 * ============================================================================
 */

import { Input, CheckBox, DatePicker } from '@ui5/webcomponents-react'
import { formatCellValue, formatDateForSap } from '../utils/displayHelpers'
import { isAutoGeneratedKeyField, isFieldReadonly, isSystemGeneratedField } from '../utils/recordHelpers'
import DomainValueHelp from './DomainValueHelp'
import FkValueHelp from './FkValueHelp'
import { FieldMeta, TableRowData } from '../types'

/* ============================================================================
 * PHAN 1: KHAI BAO INTERFACE VA PROPS CHO CELLEDITCONTROL
 * ============================================================================ */

interface CellEditControlProps {
  /** Du lieu cua toan bo dong hien tai */
  row: TableRowData
  /** Chi so vi tri cua dong trong mang editedData */
  rowIndex: number
  /** Thong tin metadata cua cot hien tai (fe_type, is_key, is_mandatory,...) */
  field: FieldMeta
  /** Danh sach cac loi validate theo tung dong va tung cot */
  inlineErrors: Record<number, Record<string, string>>
  /** UUID cua bang cau hinh dang thao tac */
  configUuid: string
  /** Ten bang ky thuat (VD: ZTPC_HEADER) */
  tableName: string
  /** Callback cap nhat gia tri moi ve hook useTableMaintenance */
  onCellChange: (rowIndex: number, fieldName: string, newValue: any) => void
}

export default function CellEditControl({
  row,
  rowIndex,
  field: f,
  inlineErrors,
  configUuid,
  tableName,
  onCellChange,
}: CellEditControlProps) {
  const name = f.field_name || f.FieldName
  const val = row[name] ?? ''
  const isNewRow = !!row._isNew
  const mode = isNewRow ? 'create' : 'edit'

  /* ============================================================================
   * PHAN 2: XU LY TRUONG READ-ONLY VA KHOA CHINH BAT BIEN
   * ============================================================================ */

  /**
   * Quy tac khoa truong khong cho phep nguoi dung sua:
   *  - Truong duoc Admin cau hinh ReadonlyFlag = 'X' trong ZFLD_CONFIG.
   *  - Truong he thong tu sinh (CREATED_BY, CHANGED_AT,...).
   *  - Truong Khoa chinh (is_key) khi dang o che do Update dong co san (de bao ve toan ven DB).
   */
  const readonly =
    isFieldReadonly(f, mode) ||
    isSystemGeneratedField(f) ||
    (mode === 'edit' && (f.is_key || f.IsKeyField === 'X'))

  if (readonly) {
    return (
      <span style={{ color: '#6a7075', fontSize: '0.875rem' }}>
        {isAutoGeneratedKeyField(f, mode) ? 'Generated automatically' : formatCellValue(f, val)}
      </span>
    )
  }

  const feType = f.fe_type || f.FeType
  // Lay cau canh bao loi validation thoi gian thuc cua o nay (neu co)
  const cellError = inlineErrors[rowIndex]?.[name]

  /* ============================================================================
   * PHAN 3: SINH LINH KIEN NHAP LIEU DONG DUA TREN FE_TYPE
   * ============================================================================ */

  // [KIEU 1: DATE] Render o chon ngay thang bang UI5 DatePicker
  if (feType === 'date') {
    const dateValue = val ? String(val).substring(0, 10) : ''
    return (
      <DatePicker
        className="table-date-picker"
        formatPattern="yyyy-MM-dd"
        value={dateValue}
        onChange={(e: any) => onCellChange(rowIndex, name, formatDateForSap(e.target.value))}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [KIEU 2: BOOLEAN] Render hop kiem Checkbox ('X' hoac '')
  if (feType === 'boolean') {
    const isChecked = val === 'X' || val === true
    return (
      <CheckBox
        checked={isChecked}
        onChange={(e: any) => onCellChange(rowIndex, name, e.target.checked ? 'X' : '')}
      />
    )
  }

  // [KIEU 3: DOMAIN] Render Dropdown chon gia tri co dinh tu tu dien DD07L
  if (feType === 'domain') {
    return (
      <DomainValueHelp
        configUuid={configUuid}
        field={f}
        value={val}
        onChange={newVal => onCellChange(rowIndex, name, newVal)}
        readonly={false}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [KIEU 4: FOREIGN KEY] Render Hop thoai tim kiem F4 tu Check Table (Search Help)
  if (feType === 'fk_select') {
    return (
      <FkValueHelp
        configUuid={configUuid}
        tableName={tableName}
        field={f}
        value={val}
        onChange={newVal => onCellChange(rowIndex, name, newVal)}
        valueState={cellError ? 'Negative' : 'None'}
        valueStateMessage={
          cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
        }
      />
    )
  }

  // [KIEU 5: TEXT / NUMBER / MAC DINH] Render the UI5 Input kem vien do ValueState khi co loi
  return (
    <Input
      value={val}
      onInput={(e: any) => onCellChange(rowIndex, name, e.target.value)}
      style={{ width: '100%' }}
      valueState={cellError ? 'Negative' : 'None'}
      valueStateMessage={
        cellError ? <div slot="valueStateMessage">{cellError}</div> : undefined
      }
    />
  )
}
