import { describe, expect, it } from 'vitest'
import {
  buildEtagMap,
  buildFullRecord,
  buildFullRecordPayload,
  buildKeyPayload,
  buildRecordKeyString,
  buildUpdateRecord,
  extractFieldFromDataJson,
  findEtagField,
  formatDeleteSummary,
  getDirtyFieldNames,
  isAutoGeneratedKeyField,
  isSystemGeneratedField,
  mergeRecordForConcurrentEdit,
  normalizeFieldValue,
  resolveEtagForUpdate,
  validateMandatory
} from './recordHelpers'

function field(overrides) {
  return {
    field_name: 'NAME',
    fe_type: 'text',
    is_key: false,
    is_mandatory: false,
    ...overrides
  }
}

const fields = [
  field({ field_name: 'MANDT', is_key: true }),
  field({ field_name: 'ENTITY_ID', fe_type: 'uuid', is_key: true }),
  field({ field_name: 'COURSE_ID', fe_type: 'text', is_key: true, label: 'Course ID' }),
  field({ field_name: 'NAME', fe_type: 'text', is_mandatory: true, label: 'Course Name' }),
  field({ field_name: 'VALID_FROM', fe_type: 'date' }),
  field({ field_name: 'ACTIVE', fe_type: 'boolean' }),
  field({ field_name: 'CHANGED_AT', fe_type: 'text' })
]

describe('recordHelpers field classification', () => {
  it('detects SAP-managed system fields', () => {
    expect(isSystemGeneratedField(field({ field_name: 'CREATED_BY' }))).toBe(true)
    expect(isSystemGeneratedField(field({ field_name: 'LAST_CHANGED_AT' }))).toBe(true)
    expect(isSystemGeneratedField(field({ field_name: 'COURSE_ID' }))).toBe(false)
  })

  it('treats UUID-like technical keys as auto-generated only in create mode', () => {
    const uuidKey = field({ field_name: 'ENTITY_ID', fe_type: 'uuid', is_key: true })
    const businessKey = field({ field_name: 'COURSE_ID', fe_type: 'text', is_key: true })

    expect(isAutoGeneratedKeyField(uuidKey, 'create')).toBe(true)
    expect(isAutoGeneratedKeyField(uuidKey, 'edit')).toBe(false)
    expect(isAutoGeneratedKeyField(businessKey, 'create')).toBe(false)
  })
})

describe('recordHelpers payloads', () => {
  it('normalizes field values by frontend type', () => {
    expect(normalizeFieldValue(field({ fe_type: 'boolean' }), true)).toBe('X')
    expect(normalizeFieldValue(field({ fe_type: 'boolean' }), false)).toBe('')
    expect(normalizeFieldValue(field({ fe_type: 'date' }), '2026-05-21')).toBe('2026-05-21')
    expect(normalizeFieldValue(field({ fe_type: 'text' }), null)).toBe('')
  })

  it('builds full create payload without SAP client or system fields', () => {
    const payload = JSON.parse(buildFullRecordPayload(fields, {
      MANDT: '324',
      ENTITY_ID: 'SHOULD_BE_GENERATED',
      COURSE_ID: 'C001',
      NAME: 'Course',
      VALID_FROM: '2026-05-21',
      ACTIVE: true,
      CHANGED_AT: '2026-05-21 14:09:48.9298540'
    }))

    expect(payload).toEqual({
      ENTITY_ID: '',
      COURSE_ID: 'C001',
      NAME: 'Course',
      VALID_FROM: '20260521',
      ACTIVE: 'X'
    })
  })

  it('builds full edit records without exposing hidden fields in the formatted payload', () => {
    const editFields = [
      field({ field_name: 'COURSE_ID', is_key: true }),
      field({ field_name: 'NAME' }),
      field({ field_name: 'SECRET_NOTE', is_hidden: true })
    ]

    expect(buildFullRecord(editFields, { COURSE_ID: 'C001', NAME: 'Changed' }, {
      COURSE_ID: 'C001',
      NAME: 'Original',
      SECRET_NOTE: 'Keep me'
    })).toEqual({
      COURSE_ID: 'C001',
      NAME: 'Changed'
    })
  })

  it('builds key payloads and key strings without client fields', () => {
    const values = {
      MANDT: '324',
      ENTITY_ID: 'i5Xzak8nH9GVo9dF0Hdi3Q==',
      COURSE_ID: 'C001'
    }

    expect(JSON.parse(buildKeyPayload(fields, values))).toEqual({
      ENTITY_ID: '8B95F36A4F271FD195A3D745D07762DD',
      COURSE_ID: 'C001'
    })
    expect(buildRecordKeyString(fields, values)).toBe(
      '{"ENTITY_ID":"8B95F36A4F271FD195A3D745D07762DD","COURSE_ID":"C001"}'
    )
  })

  it('builds update records from changed form values and original row', () => {
    const result = buildUpdateRecord(fields, { NAME: 'Changed' }, {
      ENTITY_ID: '8B95F36A4F271FD195A3D745D07762DD',
      COURSE_ID: 'C001',
      NAME: 'Original',
      VALID_FROM: '2026-05-21',
      ACTIVE: 'X'
    })

    expect(result).toMatchObject({
      ENTITY_ID: '8B95F36A4F271FD195A3D745D07762DD',
      COURSE_ID: 'C001',
      NAME: 'Changed',
      VALID_FROM: '20260521',
      ACTIVE: 'X'
    })
    expect(result).not.toHaveProperty('MANDT')
    expect(result).not.toHaveProperty('CHANGED_AT')
  })
})

describe('recordHelpers validation and dirty fields', () => {
  it('returns labels for missing mandatory fields', () => {
    expect(validateMandatory(fields, { COURSE_ID: 'C001', NAME: '' })).toEqual(['Course Name'])
  })

  it('ignores mandatory boolean fields', () => {
    expect(validateMandatory([field({ field_name: 'ACTIVE', fe_type: 'boolean', is_mandatory: true })], {})).toEqual([])
  })

  it('detects dirty field names after normalizing values', () => {
    const formFields = [
      field({ field_name: 'NAME', fe_type: 'text' }),
      field({ field_name: 'ACTIVE', fe_type: 'boolean' })
    ]

    expect(getDirtyFieldNames(formFields, { NAME: 'Old', ACTIVE: '' }, { NAME: 'New', ACTIVE: true })).toEqual([
      'NAME',
      'ACTIVE'
    ])
  })
})

describe('recordHelpers ETag handling', () => {
  const etagFields = [
    field({ field_name: 'COURSE_ID', is_key: true }),
    field({ field_name: 'NAME' }),
    field({ field_name: 'CHANGED_AT', fe_type: 'text' }),
    field({ field_name: 'CREATED_AT', fe_type: 'text' })
  ]

  it('finds the preferred ETag field from a row', () => {
    expect(findEtagField(etagFields, {
      COURSE_ID: 'C001',
      CHANGED_AT: '2026-05-21 14:09:48.9298540'
    })).toEqual({
      field: 'CHANGED_AT',
      value: '2026-05-21 14:09:48.9298540'
    })
  })

  it('extracts timestamp fields from raw backend JSON blocks', () => {
    const dataJson = '[{"COURSE_ID":"C001","CHANGED_AT":20260723155930.934}]'
    expect(extractFieldFromDataJson(dataJson, { COURSE_ID: 'C001' }, 'CHANGED_AT')).toBe('20260723155930.934')
  })

  it('builds an ETag map using backend raw JSON values', () => {
    const rows = [{ COURSE_ID: 'C001', CHANGED_AT: '2026-07-23 15:59:30.9340000' }]
    const dataJson = '[{"COURSE_ID":"C001","CHANGED_AT":20260723155930.934}]'

    expect(buildEtagMap(dataJson, etagFields, rows)).toEqual({
      '{"COURSE_ID":"C001"}': {
        field: 'CHANGED_AT',
        value: '20260723155930.934'
      }
    })
  })

  it('prefers a stored ETag when resolving update locks', () => {
    expect(resolveEtagForUpdate(
      etagFields,
      { COURSE_ID: 'C001', CHANGED_AT: '0' },
      '',
      { COURSE_ID: 'C001' },
      { field: 'CHANGED_AT', value: '2026-05-21 14:09:48.9298540' }
    )).toEqual({
      field: 'CHANGED_AT',
      value: '2026-05-21 14:09:48.9298540',
      candidates: ['2026-05-21 14:09:48.9298540']
    })
  })
})

describe('recordHelpers concurrent edit merge', () => {
  it('keeps allowed user changes and blocks fields changed by another user', () => {
    const formFields = [
      field({ field_name: 'COURSE_ID', is_key: true }),
      field({ field_name: 'NAME', label: 'Name' }),
      field({ field_name: 'STATUS', label: 'Status' })
    ]

    const result = mergeRecordForConcurrentEdit(
      formFields,
      { COURSE_ID: 'C001', NAME: 'Old Name', STATUS: 'A' },
      { COURSE_ID: 'C001', NAME: 'Old Name', STATUS: 'B' },
      { NAME: 'New Name', STATUS: 'C' },
      ['NAME', 'STATUS']
    )

    expect(result.blocked).toEqual([{ fieldName: 'STATUS', label: 'Status' }])
    expect(result.hasChanges).toBe(true)
    expect(result.fullRecord).toEqual({
      COURSE_ID: 'C001',
      NAME: 'New Name',
      STATUS: 'B'
    })
  })

  it('formats delete summaries from key labels', () => {
    expect(formatDeleteSummary(fields, { COURSE_ID: 'C001', NAME: 'Course' })).toBe(
      'MANDT: \nENTITY_ID: \nCourse ID: C001'
    )
  })
})
