import { formatDateForSap } from './displayHelpers'
import {
  formatPayload
} from './fieldMeta'
import { formatEtagValueForAbap } from './abapFormatter'
import { FieldMeta, TableRowData } from '../types'

export { formatEtagValueForAbap } from './abapFormatter'
export {
  getFormFieldsFromMeta as getFormFields,
  initFormValuesFromMeta as initFormValues,
  isDomainFieldMeta as isDomainField,
  getDomainKeyFromMeta as getDomainKey
} from './fieldMeta'

/** Audit / timestamp fields filled by SAP — not entered by user */
const SYSTEM_FIELD_NAMES = new Set([
  'CREATED_BY',
  'CREATED_AT',
  'CHANGED_BY',
  'CHANGED_AT',
  'ERNAM',
  'ERDAT',
  'ERZET',
  'AENAM',
  'AEDAT',
  'AEZET',
  'LAEDA'
])

function fieldName(field: FieldMeta): string {
  return field.field_name || field.FieldName
}

export function isSystemGeneratedField(field: FieldMeta): boolean {
  const name = fieldName(field).toUpperCase()
  if (SYSTEM_FIELD_NAMES.has(name)) return true
  if (
    name.includes('CREATED') ||
    name.includes('CHANGED') ||
    name.includes('MODIFIED') ||
    /^(CREATED|CHANGED|LAST_CHANGED|LOCAL_LAST_CHANGED)_(BY|AT|ON|DATE|TIME)$/i.test(name)
  ) {
    return true
  }
  return false
}

/** Temporary: backend does not generate keys reliably yet, so create still accepts user-entered IDs. */
export function isAutoGeneratedKeyField(_field: FieldMeta, _mode: 'create' | 'edit'): boolean {
  return false
}

export function buildKeyRecord(allFields: FieldMeta[], values: TableRowData): TableRowData {
  const keys = allFields.filter(f => {
    const isKey = f.is_key || f.IsKeyField === 'X'
    const name = (fieldName(f) || '').toUpperCase()
    return isKey && name !== 'CLIENT' && name !== 'MANDT'
  })
  const keyData: TableRowData = {}
  keys.forEach(f => {
    const name = fieldName(f)
    keyData[name] = values[name] ?? values[f.FieldName]
  })
  return JSON.parse(formatPayload(keyData, keys, false))
}

export function buildKeyPayload(allFields: FieldMeta[], values: TableRowData): string {
  const keys = allFields.filter(f => {
    const isKey = f.is_key || f.IsKeyField === 'X'
    const name = (fieldName(f) || '').toUpperCase()
    return isKey && name !== 'CLIENT' && name !== 'MANDT'
  })
  const keyData: TableRowData = {}
  keys.forEach(f => {
    const name = fieldName(f)
    keyData[name] = values[name] ?? values[f.FieldName]
  })
  return formatPayload(keyData, keys, false)
}

function mergeFormIntoRecord(allFields: FieldMeta[], formValues: Record<string, any>, originalRow: TableRowData | null, isCreate: boolean): TableRowData {
  const merged: TableRowData = {}
  allFields.forEach(f => {
    if (isSystemGeneratedField(f)) return

    const name = fieldName(f)
    // CLIENT/MANDT is always managed by SAP — never include in any payload
    if (name.toUpperCase() === 'CLIENT' || name.toUpperCase() === 'MANDT') return

    const hidden = f.is_hidden || f.HiddenFlag === 'X'

    if (hidden) {
      merged[name] = originalRow?.[name] ?? originalRow?.[f.FieldName] ?? ''
      return
    }

    if (Object.hasOwn(formValues, name)) {
      merged[name] = formValues[name]
    } else if (Object.hasOwn(formValues, f.FieldName)) {
      merged[name] = formValues[f.FieldName]
    } else if (originalRow) {
      merged[name] = originalRow[name] ?? originalRow[f.FieldName] ?? ''
    } else {
      merged[name] = normalizeFieldValue(f, '')
    }
  })
  return merged
}

export function buildFullRecord(allFields: FieldMeta[], formValues: Record<string, any>, originalRow: TableRowData | null = null): TableRowData {
  const isCreate = originalRow == null
  const merged = mergeFormIntoRecord(allFields, formValues, originalRow, isCreate)
  return JSON.parse(formatPayload(merged, allFields, isCreate))
}

export function buildFullRecordPayload(allFields: FieldMeta[], formValues: Record<string, any>, originalRow: TableRowData | null = null): string {
  const isCreate = originalRow == null
  const merged = mergeFormIntoRecord(allFields, formValues, originalRow, isCreate)
  return formatPayload(merged, allFields, isCreate)
}

export function normalizeFieldValue(field: FieldMeta, value: any): any {
  const feType = field.fe_type || field.FeType
  if (feType === 'boolean' || field.FieldType === 'CHECK') {
    return value === true || value === 'X' ? 'X' : ''
  }
  if (feType === 'date' || field.FieldType === 'DATE') {
    return formatDateForSap(value)
  }
  return value ?? ''
}

export function validateMandatory(formFields: FieldMeta[], values: Record<string, any>): string[] {
  return formFields
    .filter(f => f.is_mandatory || f.MandatoryFlag === 'X')
    .filter(f => {
      const feType = f.fe_type || f.FeType
      if (feType === 'boolean') return false
      const name = fieldName(f)
      const v = values[name] ?? values[f.FieldName]
      return v === undefined || v === null || String(v).trim() === ''
    })
    .map(f => f.label || f.LabelText || fieldName(f))
}

export function isFieldReadonly(field: FieldMeta, mode: 'create' | 'edit'): boolean {
  if (mode === 'create') return false
  if (field.is_key || field.IsKeyField === 'X') return true
  if (isAutoGeneratedKeyField(field, mode)) return true
  if (field.ReadonlyFlag === 'X' && mode === 'edit') return true
  return false
}

export function isDisplayOnlyField(field: FieldMeta, mode: 'create' | 'edit'): boolean {
  return isFieldReadonly(field, mode)
}

const ETAG_FIELD_PRIORITY = ['CHANGED_AT', 'CHANGE_AT', 'LAST_CHANGED_AT']
const ETAG_FALLBACK_FIELDS = ['CREATED_AT', 'CREATED_ON', 'ERDAT']

export function isValidEtagValue(value: any): boolean {
  if (value === 0 || value === '0') return false
  const formatted = formatEtagValueForAbap(value)
  if (formatted.length > 0) return true
  const s = String(value ?? '').trim()
  return s.length > 0 && s !== '0'
}

function fieldValuesEqual(field: FieldMeta, a: any, b: any): boolean {
  const name = fieldName(field).toUpperCase()
  const feType = field.fe_type || field.FeType
  if (
    feType === 'text' &&
    (ETAG_FIELD_PRIORITY.includes(name) || /^(CHANGED|CHANGE|LAST_CHANGED)_/i.test(name))
  ) {
    return String(a ?? '') === String(b ?? '')
  }
  if (field.FieldType === 'TIMESTAMP' || /_AT$/i.test(name)) {
    const fa = formatEtagValueForAbap(a)
    const fb = formatEtagValueForAbap(b)
    if (fa || fb) return fa === fb
    return String(a ?? '') === String(b ?? '')
  }
  return normalizeFieldValue(field, a) === normalizeFieldValue(field, b)
}

function pickEtagFromRow(allFields: FieldMeta[], row: TableRowData, fieldNames: string[]): { field: string; value: any } | null {
  for (const name of fieldNames) {
    const f = allFields.find(x => fieldName(x) === name)
    const val = row?.[name]
    if (f && val !== undefined && val !== null && val !== '' && isValidEtagValue(val)) {
      return { field: name, value: val }
    }
  }
  return null
}

export function findEtagField(allFields: FieldMeta[], row: TableRowData): { field: string; value: any } {
  if (!row || !allFields?.length) return { field: '', value: '' }

  const primary = pickEtagFromRow(allFields, row, ETAG_FIELD_PRIORITY)
  if (primary) return primary

  const fallback = pickEtagFromRow(allFields, row, ETAG_FALLBACK_FIELDS)
  if (fallback) return fallback

  for (const f of allFields) {
    if (f.is_key || f.IsKeyField === 'X') continue
    const name = fieldName(f)
    const val = row[name]
    if (/_AT$/i.test(name) && isValidEtagValue(val)) {
      return { field: name, value: val }
    }
  }

  return { field: '', value: '' }
}

function escapeRegex(s: string): string {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function findRecordBlockInDataJson(dataJson: string, recordKey: TableRowData): string | null {
  if (!dataJson || !recordKey) return null

  const keys = Object.entries(recordKey)
  if (keys.length === 0) return null

  const [primaryKey, primaryVal] = keys[0]
  const anchor = new RegExp(
    `"${escapeRegex(primaryKey)}"\\s*:\\s*"${escapeRegex(String(primaryVal))}"`,
    'i'
  )
  const anchorMatch = anchor.exec(dataJson)
  if (!anchorMatch) return null

  const anchorIdx = anchorMatch.index
  const objStart = dataJson.lastIndexOf('{', anchorIdx)
  const objEnd = dataJson.indexOf('}', anchorIdx)
  if (objStart < 0 || objEnd <= objStart) return null

  const block = dataJson.slice(objStart, objEnd + 1)

  for (const [k, v] of keys.slice(1)) {
    const keyPattern = new RegExp(
      `"${escapeRegex(k)}"\\s*:\\s*"${escapeRegex(String(v))}"`,
      'i'
    )
    if (!keyPattern.test(block)) return null
  }

  return block
}

export function extractFieldFromDataJson(dataJson: string, recordKey: TableRowData, fieldName: string): string | null {
  const block = findRecordBlockInDataJson(dataJson, recordKey)
  if (!block || !fieldName) return null

  const fieldMatch = block.match(
    new RegExp(
      `"${escapeRegex(fieldName)}"\\s*:\\s*("([^"]*)"|(\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d+)|(\\d{14}\\.\\d+)|(\\d{14})|null|0)`,
      'i'
    )
  )
  if (!fieldMatch) return null

  if (fieldMatch[2] !== undefined) return fieldMatch[2]
  if (fieldMatch[3] !== undefined) return fieldMatch[3]
  if (fieldMatch[4] !== undefined) return fieldMatch[4]
  if (fieldMatch[5] !== undefined) {
    const d = fieldMatch[5]
    return `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)} ${d.slice(8, 10)}:${d.slice(10, 12)}:${d.slice(12, 14)}.0000000`
  }
  return null
}

export function extractEtagFromDataJson(dataJson: string, recordKey: TableRowData, etagFieldName: string): string | null {
  return extractFieldFromDataJson(dataJson, recordKey, etagFieldName)
}

export function buildRecordKeyString(allFields: FieldMeta[], row: TableRowData): string {
  return JSON.stringify(buildKeyRecord(allFields, row))
}

export function buildEtagMap(dataJson: string, allFields: FieldMeta[], rows: TableRowData[]): Record<string, { field: string; value: string }> {
  if (!dataJson || !allFields?.length || !rows?.length) return {}

  const map: Record<string, { field: string; value: string }> = {}
  for (const row of rows) {
    const recordKey = buildKeyRecord(allFields, row)
    const keyStr = buildRecordKeyString(allFields, row)
    const { field, value } = findEtagField(allFields, row)
    if (!field) continue

    const raw = extractEtagFromDataJson(dataJson, recordKey, field)
    if (raw !== null && raw !== undefined) {
      map[keyStr] = { field, value: String(raw) }
      continue
    }

    const formatted = formatEtagValueForAbap(value)
    if (formatted) {
      map[keyStr] = { field, value: formatted }
    } else if (value !== undefined && value !== null && String(value).trim() !== '') {
      map[keyStr] = { field, value: String(value) }
    }
  }
  return map
}

export interface EtagInfo {
  field: string;
  value: string;
  candidates?: string[];
}

export function resolveEtagForUpdate(
  allFields: FieldMeta[],
  row: TableRowData,
  dataJson: string,
  recordKey: TableRowData,
  storedEtag: { field: string; value: string } | null = null
): EtagInfo {
  if (storedEtag?.field && storedEtag?.value) {
    const raw = String(storedEtag.value).trim()
    if (raw && raw !== '0') {
      const formatted = formatEtagValueForAbap(raw)
      const value = formatted || raw
      return { field: storedEtag.field, value, candidates: [value] }
    }
    return { field: storedEtag.field, value: '', candidates: [] }
  }

  const { field, value } = findEtagField(allFields, row)
  if (!field) return { field: '', value: '', candidates: [] }

  if (dataJson && recordKey) {
    const raw = extractEtagFromDataJson(dataJson, recordKey, field)
    if (raw !== null && raw !== undefined && String(raw).trim() !== '' && raw !== '0') {
      const formatted = formatEtagValueForAbap(raw)
      const etagVal = formatted || String(raw)
      return { field, value: etagVal, candidates: [etagVal] }
    }
  }

  const formatted = formatEtagValueForAbap(value)
  if (!formatted && (value === undefined || value === null || String(value).trim() === '')) {
    return { field: '', value: '', candidates: [] }
  }

  const etagVal = formatted || String(value)
  return { field, value: etagVal, candidates: [etagVal] }
}

export function formatEtagForUpdate(
  allFields: FieldMeta[],
  row: TableRowData,
  dataJson = '',
  recordKey: TableRowData | null = null,
  storedEtag: { field: string; value: string } | null = null
): EtagInfo {
  return resolveEtagForUpdate(allFields, row, dataJson, recordKey || {}, storedEtag)
}

export function buildUpdateRecord(
  allFields: FieldMeta[],
  formValues: Record<string, any>,
  originalRow: TableRowData | null = null,
  _dataJson = '',
  _recordKey: TableRowData | null = null
): TableRowData {
  const merged = mergeFormIntoRecord(allFields, formValues, originalRow, false)
  return JSON.parse(formatPayload(merged, allFields, false))
}

export function buildUpdateRecordPayload(allFields: FieldMeta[], formValues: Record<string, any>, originalRow: TableRowData | null = null): string {
  const merged = mergeFormIntoRecord(allFields, formValues, originalRow, false)
  return formatPayload(merged, allFields, false)
}

export function getDirtyFieldNames(formFields: FieldMeta[], baselineRow: TableRowData | null, formValues: Record<string, any>): string[] {
  if (!baselineRow) return []
  return formFields
    .filter(f => {
      const name = fieldName(f)
      const before = normalizeFieldValue(f, baselineRow[name] ?? baselineRow[f.FieldName])
      const after = normalizeFieldValue(f, formValues[name] ?? formValues[f.FieldName])
      return before !== after
    })
    .map(f => fieldName(f))
}

export interface MergeResult {
  fullRecord: TableRowData;
  blocked: Array<{ fieldName: string; label: string }>;
  hasChanges: boolean;
}

export function mergeRecordForConcurrentEdit(
  allFields: FieldMeta[],
  baselineRow: TableRowData,
  freshRow: TableRowData,
  formValues: Record<string, any>,
  dirtyFieldNames: string[],
  dataJson = '',
  recordKey: TableRowData | null = null
): MergeResult {
  const blocked: Array<{ fieldName: string; label: string }> = []
  const allowedChanges: Record<string, any> = {}

  for (const fieldNameKey of dirtyFieldNames) {
    const field = allFields.find(f => fieldName(f) === fieldNameKey)
    if (!field) continue

    const label = field.label || field.LabelText || fieldNameKey
    const key = fieldName(field)
    if (!fieldValuesEqual(field, baselineRow[key], freshRow[key])) {
      blocked.push({ fieldName: fieldNameKey, label })
      continue
    }

    allowedChanges[key] = normalizeFieldValue(
      field,
      formValues[key] ?? formValues[field.FieldName]
    )
  }

  const key = recordKey ?? buildKeyRecord(allFields, freshRow)
  const fullRecord = buildUpdateRecord(
    allFields,
    allowedChanges,
    freshRow,
    dataJson,
    key
  )

  return {
    fullRecord,
    blocked,
    hasChanges: Object.keys(allowedChanges).length > 0
  }
}

export function formatDeleteSummary(allFields: FieldMeta[], row: TableRowData): string {
  const keys = allFields.filter(f => f.is_key || f.IsKeyField === 'X')
  if (keys.length === 0) {
    return Object.entries(row)
      .slice(0, 3)
      .map(([k, v]) => `${k}: ${v}`)
      .join(', ')
  }
  return keys
    .map(f => `${f.label || f.LabelText || fieldName(f)}: ${row[fieldName(f)] ?? ''}`)
    .join('\n')
}
