import { FieldMeta, TableRowData } from '../types'
import { isAutoGeneratedKeyField, isForeignKeyField } from './recordHelpers'

export function getMaxTextLength(field: FieldMeta): number {
  const len = field.length || field.Length || 0

  if (isUuidField(field)) {
    return 32
  }

  return len
}

function isUuidField(field: FieldMeta): boolean {
  const feType = String(field.fe_type || field.FeType || '').toLowerCase()
  const fieldType = String(
    field.abap_type ||
    field.FieldType ||
    ''
  ).toUpperCase()
  const length = Number(field.length || field.Length || 0)

  return (
    feType === 'uuid' ||
    fieldType === 'UUID' ||
    fieldType === 'RAW16' ||
    (fieldType === 'X' && length === 16) ||
    (fieldType === 'RAW' && length === 16)
  )
}

export function validateFieldLength(field: FieldMeta, val: any): string {
  const feType = field.fe_type || field.FeType
  const maxLength = getMaxTextLength(field)
  const uuidInput = isUuidField(field)

  if (maxLength > 0 && feType === 'text' && !uuidInput) {
    if (String(val).length > maxLength) {
      return `Maximum length is ${maxLength} characters`
    }
  }

  if (uuidInput) {
    const raw = String(val ?? '').trim()
    if (!raw) return ''

    const compact = raw.replace(/-/g, '')
    if (compact.length > 32) {
      return 'Maximum length is 32 hex characters'
    }
    if (compact.length > 0 && !/^[0-9A-F]+$/i.test(compact)) {
      return 'UUID must contain only hexadecimal characters'
    }
  }

  return ''
}

export function getDuplicateCheckKeyFields(fields: FieldMeta[]): FieldMeta[] {
  return fields.filter(f => {
    const isKey = f.is_key || f.IsKeyField === 'X'
    const name = (f.field_name || f.FieldName || '').toUpperCase()
    return isKey && name !== 'CLIENT' && name !== 'MANDT' && !isAutoGeneratedKeyField(f, 'create')
  })
}

export function shouldCheckDuplicateKey(keyFields: FieldMeta[]): boolean {
  return keyFields.some(f => !isForeignKeyField(f))
}

/**
 * Validates a single inline-edited cell value.
 * Returns an error message string, or '' if valid.
 *
 * @param rowIndex       - Index of the row being validated
 * @param fieldNameKey   - Technical field name
 * @param val            - Current cell value
 * @param row            - Full row data (may be an updated draft)
 * @param allFields      - All field metadata for the table
 * @param data           - Committed database rows (for duplicate key check)
 * @param editedData     - Current in-flight edited rows (for cross-row duplicate check)
 */
export function validateInlineField(
  rowIndex: number,
  fieldNameKey: string,
  val: any,
  row: TableRowData,
  allFields: FieldMeta[],
  data: TableRowData[],
  editedData: TableRowData[]
): string {
  const field = allFields.find(f => (f.field_name || f.FieldName) === fieldNameKey)
  if (!field) return ''

  const isKey = field.is_key || field.IsKeyField === 'X'
  const feType = field.fe_type || field.FeType
  const isAutoGeneratedCreateKey = row._isNew && isAutoGeneratedKeyField(field, 'create')

  if (isAutoGeneratedCreateKey) return ''

  // 1. Mandatory validation
  const isMandatory = field.is_mandatory || field.MandatoryFlag === 'X'
  if (isMandatory && feType !== 'boolean') {
    if (val === undefined || val === null || String(val).trim() === '') {
      return 'Field is required'
    }
  }

  // 2. Length validation
  const lengthError = validateFieldLength(field, val)
  if (lengthError) return lengthError

  // 3. Numeric validation (integer & decimal)
  const isNumeric = feType === 'integer' || feType === 'decimal' || feType === 'number'
  if (isNumeric && val !== undefined && val !== null && String(val).trim() !== '') {
    const strVal = String(val).trim()
    if (feType === 'integer') {
      if (!/^-?\d+$/.test(strVal)) {
        return 'Must be a valid integer'
      }
    } else {
      if (!/^-?\d+(\.\d+)?$/.test(strVal)) {
        return 'Must be a valid number'
      }
    }
  }

  // 3. Duplicate Key Check
  if (row._isNew && isKey) {
    const keyFields = getDuplicateCheckKeyFields(allFields)
    if (!shouldCheckDuplicateKey(keyFields)) return ''

    const hasAllKeys = keyFields.every(kf => {
      const name = kf.field_name || kf.FieldName
      const kVal = row[name]
      return kVal !== undefined && kVal !== null && String(kVal).trim() !== ''
    })

    if (hasAllKeys) {
      const buildKeyString = (r: TableRowData) =>
        keyFields
          .map(kf => {
            const name = kf.field_name || kf.FieldName
            return String(r[name] ?? r[kf.FieldName] ?? '').trim().toUpperCase()
          })
          .join('|')

      const currentKeyStr = buildKeyString(row)

      const duplicateInDb = data.some(dbRow => buildKeyString(dbRow) === currentKeyStr)
      if (duplicateInDb) {
        return 'Primary Key combination already exists!'
      }

      const duplicateInEdited = editedData.some((otherRow, otherIdx) => {
        if (otherIdx === rowIndex || !otherRow._isNew) return false
        return buildKeyString(otherRow) === currentKeyStr
      })
      if (duplicateInEdited) {
        return 'Duplicate key found in another new row!'
      }
    }
  }

  return ''
}
