/**
 * ============================================================================
 * FILE: src/pages/TableMaintenance/hooks/useTableMaintenance.ts
 * ----------------------------------------------------------------------------
 * VAI TRO: Bo nao nghiep vu CRUD, Khoa bang & Xu ly dong thoi (Custom Hook Core).
 * ----------------------------------------------------------------------------
 * CAC NHIEM VU CHINH:
 *   - 1. Quan ly toan bo State: Metadata (fields), Du lieu (data), Bo loc (filters), Dialogs.
 *   - 2. Quan ly Khoa bang (Application Lock ZTBL_LOCK) & Heartbeat dinh ky de tranh xung dot nhieu nguoi sua.
 *   - 3. Xu ly luong Chinh sua Inline & Form Dialog (Add Row, Remove Row, Live Validation).
 *   - 4. Thuc thi Luu du lieu (Save): Phan tach Create/Update, Bulk Create/Update va phan luong Phe duyet Approval.
 *   - 5. Kiem soat xung dot dong thoi qua ETag (Optimistic Concurrency Control) & Xu ly loi Khoa ngoai (FK Errors).
 * ============================================================================
 */

import { useState, useEffect, useRef, useId } from 'react'
import {
  loadTableContext,
  getTableData,
  createRecord,
  bulkCreateRecords,
  updateRecord,
  bulkUpdateRecords,
  deleteRecord,
  bulkDeleteRecords,
  parseTableDataJson,
  getFriendlyErrorMessage,
  formatActionErrorMessage,
  getActionMessage,
  parseBulkActionResults,
  normalizeConfigUuid,
  isOptimisticLockError,
  isFKReferenceError,
  parseFKErrorMessage,
  getPendingApprovalRecords
} from '../../../services/tableConfigApi'
import { clearDomainCache } from '../../../services/domainCache'
import {
  buildKeyRecord,
  buildRecordKeyString,
  buildFullRecord,
  buildFullRecordPayload,
  buildUpdateRecord,
  buildEtagMap,
  resolveEtagForUpdate,
  mergeRecordForConcurrentEdit,
  initFormValues,
  validateMandatory,
  isFieldReadonly,
  isSystemGeneratedField,
  isAutoGeneratedKeyField
} from '../../../utils/recordHelpers'
import { getDuplicateCheckKeyFields, validateInlineField } from '../../../utils/validationHelpers'
import { extractApprovalCode, isYesFlag } from '../../../utils/tableHelpers'
import {
  acquireTableLock,
  releaseTableLock,
  getActiveTableLock,
  touchTableLock
} from '../../../utils/tableLockService'
import { FieldMeta, PendingApprovalRecord, TableConfig, TableRowData } from '../../../types'

export interface TableMaintenancePageProps {
  selectedTable: TableConfig | null
  tables: TableConfig[]
  username: string
  onRefreshTableList: () => Promise<void>
  onSelectTable: (table: TableConfig | null) => void
}

export function useTableMaintenance({
  selectedTable,
  username,
  onRefreshTableList
}: TableMaintenancePageProps) {
  /* ============================================================================
   * PHAN 1: KHAI BAO TOAN BO STATE CUA HOOK
   * ============================================================================ */

  // ─── Du lieu & Metadata ───────────────────────────────────────────────────
  const [allFields, setAllFields] = useState<FieldMeta[]>([])
  const [fields, setFields] = useState<FieldMeta[]>([])
  const [data, setData] = useState<TableRowData[]>([])
  const [tableDataJson, setTableDataJson] = useState('')
  const [etagMap, setEtagMap] = useState<Record<string, { field: string; value: string }>>({})
  const [editSessionEtag, setEditSessionEtag] = useState<any>(null)
  const [pendingApprovalRecords, setPendingApprovalRecords] = useState<PendingApprovalRecord[]>([])

  // ─── Trang thai giao dien & Thong bao ─────────────────────────────────────
  const [dataLoading, setDataLoading] = useState(false)
  const [error, setError] = useState('')
  const [successMsg, setSuccessMsg] = useState('')

  // ─── Bo loc & Tim kiem ────────────────────────────────────────────────────
  const [searchQuery, setSearchQuery] = useState('')
  const [filterValues, setFilterValues] = useState<Record<string, string>>({})
  const [appliedSearchQuery, setAppliedSearchQuery] = useState('')
  const [appliedFilterValues, setAppliedFilterValues] = useState<Record<string, string>>({})

  // ─── Che do Chinh sua Inline ──────────────────────────────────────────────
  const [isEditingTable, setIsEditingTable] = useState(false)
  const [editedData, setEditedData] = useState<TableRowData[]>([])
  const [inlineErrors, setInlineErrors] = useState<Record<number, Record<string, string>>>({})

  // ─── Dialog Them/Sua ban ghi ──────────────────────────────────────────────
  const [recordDialogOpen, setRecordDialogOpen] = useState(false)
  const [recordDialogMode, setRecordDialogMode] = useState<'create' | 'edit'>('create')
  const [editingRow, setEditingRow] = useState<TableRowData | null>(null)

  // ─── Dialog Xac nhan Xoa ──────────────────────────────────────────────────
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false)
  const [deletingRows, setDeletingRows] = useState<TableRowData[]>([])
  const [deleteLoading, setDeleteLoading] = useState(false)

  // ─── Dialogs Bao loi dac thu (ETag Conflict, Khoa ngoai FK) ───────────────
  const [optimisticLockOpen, setOptimisticLockOpen] = useState(false)
  const [fkErrorOpen, setFkErrorOpen] = useState(false)
  const [fkErrorMessage, setFkErrorMessage] = useState('')

  // ─── Toast thong bao & Phe duyet Approval ────────────────────────────────
  const [toastMessage, setToastMessage] = useState('')
  const [toastOpen, setToastOpen] = useState(false)
  const [approvalInfo, setApprovalInfo] = useState<{
    code: string
    action: 'create' | 'update' | 'delete' | 'save'
  } | null>(null)

  // ─── Khoa bang (Application Lock ZTBL_LOCK) ───────────────────────────────
  const [activeTableLock, setActiveTableLock] = useState<{ lockedBy: string } | null>(null)

  const latestActiveTableUuidRef = useRef<string | null>(null)
  const loadingTableUuidRef = useRef<string | null>(null)
  const sessionId = useId()

  // ─── Cac ham tro giup (Helpers) ───────────────────────────────────────────
  function showError(message: string) {
    setSuccessMsg('')
    setError(message)
  }

  function showSuccess(message: string) {
    setError('')
    setSuccessMsg(message)
  }

  function showToast(message: string) {
    setError('')
    setSuccessMsg('')
    setToastMessage(message)
    setToastOpen(true)
  }

  function chunkRecords<T>(records: T[], size = 50): T[][] {
    const chunks: T[][] = []
    for (let i = 0; i < records.length; i += size) {
      chunks.push(records.slice(i, i + size))
    }
    return chunks
  }

  function getBulkFailures(response: any): { record_index: number; message: string }[] {
    return parseBulkActionResults(response)
      .filter(item => !item.success)
      .map(item => ({
        record_index: item.record_index,
        message: item.message || 'Operation failed',
      }))
  }

  function formatBulkFailureMessage(action: string, failures: { record_index: number; message: string }[]): string {
    const preview = failures
      .slice(0, 3)
      .map(item => `#${item.record_index}: ${item.message}`)
      .join(' | ')
    return `${failures.length} record(s) failed during bulk ${action}${preview ? `: ${preview}` : ''}`
  }

  function findOriginalRow(row: TableRowData): TableRowData | null {
    const keyStr = buildRecordKeyString(allFields, row)
    return data.find(orig => buildRecordKeyString(allFields, orig) === keyStr) || null
  }

  function buildInlineUpdateRecord(row: TableRowData): TableRowData {
    const originalRow = findOriginalRow(row)
    return buildUpdateRecord(allFields, row, originalRow, tableDataJson, buildKeyRecord(allFields, row))
  }

  function clearPageData() {
    setAllFields([])
    setFields([])
    setData([])
    setTableDataJson('')
    setEtagMap({})
    setPendingApprovalRecords([])
    clearDomainCache()
    setSearchQuery('')
    setFilterValues({})
    setAppliedSearchQuery('')
    setAppliedFilterValues({})
    setIsEditingTable(false)
    setEditedData([])
    setInlineErrors({})
  }

  /* ============================================================================
   * PHAN 2: QUAN LY KHOA BANG (APPLICATION LOCK & HEARTBEAT)
   * ============================================================================ */

  /**
   * Xin khoa bang ZTBL_LOCK khi nguoi dung bat dau bam Create hoac Edit.
   * Neu bang dang bi nguoi khac khoa -> Tra ve false va hien thong bao chan.
   */
  function tryStartEditingTable(): boolean {
    if (!selectedTable) return false
    const lockRes = acquireTableLock(selectedTable.TableName, username, sessionId)
    if (!lockRes.acquired) {
      showError(`Cannot edit: Table is currently being edited by User ${lockRes.heldBy}`)
      return false
    }
    setError('')
    return true
  }

  function releaseTableLockIfHeld() {
    if (selectedTable) {
      releaseTableLock(selectedTable.TableName, sessionId)
    }
  }

  /**
   * [Effect Polling & Heartbeat]:
   * - Kiem tra trang thai khoa dinh ky moi 5 giay.
   * - Neu dang o che do Edit, gui touchTableLock (Heartbeat) de duy tri thoi gian song TTL = 300s.
   * - Khi thoat component hoac dong tab, tu dong giai phong khoa (releaseTableLock).
   */
  useEffect(() => {
    if (!selectedTable) {
      setActiveTableLock(null)
      return undefined
    }

    const checkLock = () => {
      const lock = getActiveTableLock(selectedTable.TableName, username, sessionId)
      setActiveTableLock(lock)
      if (isEditingTable || recordDialogOpen || deleteDialogOpen) {
        touchTableLock(selectedTable.TableName, sessionId)
      }
    }

    checkLock()
    const interval = setInterval(checkLock, 5000)
    const handleStorageChange = () => checkLock()
    window.addEventListener('storage', handleStorageChange)

    return () => {
      clearInterval(interval)
      window.removeEventListener('storage', handleStorageChange)
      releaseTableLock(selectedTable.TableName, sessionId)
    }
  }, [selectedTable, username, sessionId, isEditingTable, recordDialogOpen, deleteDialogOpen])

  /* ============================================================================
   * PHAN 3: NAP DU LIEU BANG VA METADATA (LOAD TABLE)
   * ============================================================================ */

  // Tu dong load bang khi selectedTable thay doi
  useEffect(() => {
    if (selectedTable) {
      loadTable(selectedTable)
    } else {
      clearPageData()
    }
  }, [selectedTable?.ConfigUuid])

  // Dinh ky cap nhat trang thai cac dong dang cho duyet (Pending Approval)
  useEffect(() => {
    if (!selectedTable || !isYesFlag(selectedTable.ApprovalRequired)) return undefined

    let cancelled = false
    const normalizedUuid = normalizeConfigUuid(selectedTable.ConfigUuid)
    const refreshPendingState = async () => {
      const records = await fetchPendingApprovalState(selectedTable)
      if (!cancelled && records && records.length > 0 && latestActiveTableUuidRef.current === normalizedUuid) {
        setPendingApprovalRecords(records)
      }
    }

    const interval = window.setInterval(refreshPendingState, 30000)
    window.addEventListener('focus', refreshPendingState)

    return () => {
      cancelled = true
      window.clearInterval(interval)
      window.removeEventListener('focus', refreshPendingState)
    }
  }, [selectedTable?.ConfigUuid, selectedTable?.ApprovalRequired])

  useEffect(() => {
    if (!successMsg) return
    const timer = setTimeout(() => setSuccessMsg(''), 3000)
    return () => clearTimeout(timer)
  }, [successMsg])

  async function fetchPendingApprovalState(table: TableConfig): Promise<PendingApprovalRecord[] | null> {
    if (!isYesFlag(table.ApprovalRequired)) return []
    try {
      return await getPendingApprovalRecords(table.TableName)
    } catch (error: any) {
      console.warn('Cannot load pending approval state:', error?.message || error)
      return null
    }
  }

  /**
   * [HAM loadTable]: Goi dong thoi Action getFieldMeta va getTableData tu SAP.
   * Xay dung danh sach fields metadata, mảng du lieu rows va ban do etagMap.
   */
  async function loadTable(table: TableConfig) {
    const normalizedUuid = normalizeConfigUuid(table.ConfigUuid)
    if (loadingTableUuidRef.current === normalizedUuid) return

    loadingTableUuidRef.current = normalizedUuid
    const isChangingTable = latestActiveTableUuidRef.current !== normalizedUuid
    latestActiveTableUuidRef.current = normalizedUuid

    setAllFields([])
    setFields([])
    setData([])
    setTableDataJson('')
    setEtagMap({})
    if (isChangingTable) setPendingApprovalRecords([])
    setSearchQuery('')
    setFilterValues({})
    setAppliedSearchQuery('')
    setAppliedFilterValues({})
    setIsEditingTable(false)
    setEditedData([])
    setInlineErrors({})

    try {
      setDataLoading(true)
      setError('')
      setSuccessMsg('')

      const [tableContext, pendingRecords] = await Promise.all([
        loadTableContext(normalizedUuid, table.TableName),
        fetchPendingApprovalState(table)
      ])
      const { fieldMeta, tableData, rows } = tableContext

      if (latestActiveTableUuidRef.current !== normalizedUuid) return

      setAllFields(fieldMeta)
      setFields(fieldMeta.filter(f => !f.is_hidden && f.HiddenFlag !== 'X'))

      const dataJson = tableData.data_json || ''
      setData(rows)
      setTableDataJson(dataJson)
      setEtagMap(dataJson ? buildEtagMap(dataJson, fieldMeta, rows) : {})
      if (pendingRecords && pendingRecords.length > 0) {
        setPendingApprovalRecords(pendingRecords)
      } else if (isChangingTable) {
        setPendingApprovalRecords([])
      }
    } catch (e: any) {
      if (latestActiveTableUuidRef.current === normalizedUuid) {
        showError(getFriendlyErrorMessage(e))
        clearPageData()
      }
    } finally {
      if (loadingTableUuidRef.current === normalizedUuid) {
        loadingTableUuidRef.current = null
      }
      if (latestActiveTableUuidRef.current === normalizedUuid) {
        setDataLoading(false)
      }
    }
  }

  /* ============================================================================
   * PHAN 4: XU LY CHINH SUA INLINE (LIVE VALIDATION, ADD ROW, REMOVE ROW)
   * ============================================================================ */

  function validateCell(
    rowIndex: number,
    fieldNameKey: string,
    val: any,
    row: TableRowData,
    currentEditedData?: TableRowData[]
  ): string {
    return validateInlineField(
      rowIndex,
      fieldNameKey,
      val,
      row,
      allFields,
      data,
      currentEditedData ?? editedData
    )
  }

  /**
   * Xu ly khi user go chu hoac chon gia tri tren tung o.
   * Tu dong chay validate thoi gian thuc va kiem tra trung khoa chinh (Duplicate Key).
   */
  const handleCellChange = (rowIndex: number, fieldName: string, newValue: any) => {
    setEditedData(prev => {
      const updated = [...prev]
      const updatedRow = { ...updated[rowIndex], [fieldName]: newValue }
      updated[rowIndex] = updatedRow

      setInlineErrors(prevErrors => {
        const nextErrors = { ...prevErrors }
        const rowErrors = { ...(nextErrors[rowIndex] || {}) }
        const errorMsg = validateCell(rowIndex, fieldName, newValue, updatedRow, updated)
        if (errorMsg) {
          rowErrors[fieldName] = errorMsg
        } else {
          delete rowErrors[fieldName]
        }

        // Re-validate sibling key fields
        const field = allFields.find(f => (f.field_name || f.FieldName) === fieldName)
        if (field && (field.is_key || field.IsKeyField === 'X') && updatedRow._isNew) {
          const otherKeys = getDuplicateCheckKeyFields(allFields).filter(
            f => (f.field_name || f.FieldName) !== fieldName
          )
          otherKeys.forEach(ok => {
            const okName = ok.field_name || ok.FieldName
            const okVal = updatedRow[okName] ?? ''
            const okErr = validateCell(rowIndex, okName, okVal, updatedRow, updated)
            if (okErr) {
              rowErrors[okName] = okErr
            } else {
              delete rowErrors[okName]
            }
          })
        }

        if (Object.keys(rowErrors).length > 0) {
          nextErrors[rowIndex] = rowErrors
        } else {
          delete nextErrors[rowIndex]
        }

        // Re-validate all other new rows
        if (field && (field.is_key || field.IsKeyField === 'X') && updatedRow._isNew) {
          updated.forEach((otherRow, otherIdx) => {
            if (otherIdx === rowIndex || !otherRow._isNew) return

            const otherRowErrors = { ...(nextErrors[otherIdx] || {}) }
            const keyFields = getDuplicateCheckKeyFields(allFields)
            let keyChanged = false
            keyFields.forEach(kf => {
              const kfName = kf.field_name || kf.FieldName
              const kfVal = otherRow[kfName] ?? ''
              const kfErr = validateCell(otherIdx, kfName, kfVal, otherRow, updated)
              if (kfErr) {
                otherRowErrors[kfName] = kfErr
                keyChanged = true
              } else if (otherRowErrors[kfName]) {
                delete otherRowErrors[kfName]
                keyChanged = true
              }
            })
            if (keyChanged) {
              if (Object.keys(otherRowErrors).length > 0) {
                nextErrors[otherIdx] = otherRowErrors
              } else {
                delete nextErrors[otherIdx]
              }
            }
          })
        }

        return nextErrors
      })

      return updated
    })
  }

  /** Them 1 dong moi len dau bang nhap lieu voi co _isNew = true */
  const handleAddRow = () => {
    const newRecord = initFormValues(allFields, null)
    newRecord._isNew = true
    setEditedData(prev => [newRecord, ...prev])
    setInlineErrors(prevErrors => {
      const nextErrors: Record<number, Record<string, string>> = {}
      Object.entries(prevErrors).forEach(([idxStr, errs]) => {
        const idx = parseInt(idxStr, 10)
        nextErrors[idx + 1] = errs
      })
      return nextErrors
    })
  }

  const handleCancelInlineEdits = () => {
    setIsEditingTable(false)
    setEditedData([])
    setInlineErrors({})
    setError('')
    releaseTableLockIfHeld()
  }

  const handleRemoveNewRow = (rowIndex: number) => {
    setEditedData(prev => {
      const updated = prev.filter((_, idx) => idx !== rowIndex)

      setInlineErrors(prevErrors => {
        const nextErrors: Record<number, Record<string, string>> = {}
        Object.entries(prevErrors).forEach(([idxStr, errs]) => {
          const idx = parseInt(idxStr, 10)
          if (idx < rowIndex) {
            nextErrors[idx] = errs
          } else if (idx > rowIndex) {
            nextErrors[idx - 1] = errs
          }
        })

        updated.forEach((row, idx) => {
          if (!row._isNew) return
          const keyFields = getDuplicateCheckKeyFields(allFields)
          const rowErrors = { ...(nextErrors[idx] || {}) }
          let keyChanged = false
          keyFields.forEach(kf => {
            const kfName = kf.field_name || kf.FieldName
            const kfVal = row[kfName] ?? ''
            const kfErr = validateCell(idx, kfName, kfVal, row, updated)
            if (kfErr) {
              rowErrors[kfName] = kfErr
              keyChanged = true
            } else if (rowErrors[kfName]) {
              delete rowErrors[kfName]
              keyChanged = true
            }
          })
          if (keyChanged) {
            if (Object.keys(rowErrors).length > 0) {
              nextErrors[idx] = rowErrors
            } else {
              delete nextErrors[idx]
            }
          }
        })

        return nextErrors
      })

      return updated
    })
  }

  /* ============================================================================
   * PHAN 5: LUONG LUU DU LIEU INLINE (handleSaveInlineEdits)
   * ============================================================================ */

  /**
   * [HAM handleSaveInlineEdits]:
   *  - 1. Validate bat buoc (Mandatory).
   *  - 2. Loc ra danh sach dong moi (newRows) va dong bi sua (modifiedRows).
   *  - 3. Goi createRecord / bulkCreateRecords cho dong moi.
   *  - 4. Goi updateRecord / bulkUpdateRecords kem ETag cho dong sua.
   *  - 5. Hien thi thong bao Phe duyet Approval hoac Luu thanh cong.
   *  - 6. Giai phong khoa va reload lai bang.
   */
  async function handleSaveInlineEdits() {
    if (!selectedTable) return
    setError('')
    setSuccessMsg('')

    // 1. Kiem tra truong bat buoc
    const validationErrors: string[] = []
    const newInlineErrors = { ...inlineErrors }
    let hasValidationError = false

    editedData.forEach((row, idx) => {
      const mandatoryFields = row._isNew
        ? fields.filter(f => !isAutoGeneratedKeyField(f, 'create'))
        : fields
      const missing = validateMandatory(mandatoryFields, row)
      if (missing.length > 0) {
        validationErrors.push(`Row #${idx + 1}: Missing required fields: ${missing.join(', ')}`)
        hasValidationError = true
        const rowErrs = { ...(newInlineErrors[idx] || {}) }
        missing.forEach(name => { rowErrs[name] = 'Field is required' })
        newInlineErrors[idx] = rowErrs
      }
    })

    if (hasValidationError) {
      setInlineErrors(newInlineErrors)
      showError(validationErrors.join(' | '))
      return
    }

    if (Object.values(inlineErrors).some(row => Object.keys(row).length > 0)) {
      showError('Please fix validation errors before saving.')
      return
    }

    try {
      setDataLoading(true)

      const newRows = editedData.filter(r => r._isNew)
      const modifiedRows = editedData.filter(row => {
        if (row._isNew) return false
        const keyStr = buildRecordKeyString(allFields, row)
        const originalRow = data.find(orig => buildRecordKeyString(allFields, orig) === keyStr)
        if (!originalRow) return true
        return fields.some(f => {
          if (isSystemGeneratedField(f)) return false
          const name = f.field_name || f.FieldName
          return row[name] !== originalRow[name]
        })
      })

      if (newRows.length === 0 && modifiedRows.length === 0) {
        showSuccess('No changes to save')
        setIsEditingTable(false)
        setEditedData([])
        return
      }

      const approvalCodes: string[] = []
      const successMessages: string[] = []

      // [CREATE] Tao dong moi duoi SAP
      if (newRows.length === 1) {
        const row = newRows[0]
        const payload = buildFullRecordPayload(allFields, row, null)
        const res = await createRecord(selectedTable.ConfigUuid, selectedTable.TableName, payload)
        if (res.success === false) throw new Error(getActionMessage(res) || res.message || 'Failed to create record')
        const msg = getActionMessage(res) || res.message || res.value?.message || res.data?.message || res.data?.value?.message
        if (msg && !successMessages.includes(msg)) successMessages.push(msg)
        const code = extractApprovalCode(res)
        if (code && !approvalCodes.includes(code)) approvalCodes.push(code)
      } else if (newRows.length > 1) {
        for (const chunk of chunkRecords(newRows)) {
          const records = chunk.map(row => buildFullRecord(allFields, row, null))
          const res = await bulkCreateRecords(
            selectedTable.ConfigUuid,
            selectedTable.TableName,
            records
          )
          if (res.success === false) throw new Error(getActionMessage(res) || res.message || 'Failed to create records')

          const failures = getBulkFailures(res)
          if (failures.length > 0) {
            throw new Error(formatBulkFailureMessage('create', failures))
          }

          const msg = getActionMessage(res) || res.message || res.value?.message || res.data?.message || res.data?.value?.message
          if (msg && !successMessages.includes(msg)) successMessages.push(msg)
          const code = extractApprovalCode(res)
          if (code && !approvalCodes.includes(code)) approvalCodes.push(code)
        }
      }

      // [UPDATE] Cap nhat dong co san kem ETag
      if (modifiedRows.length === 1) {
        const row = modifiedRows[0]
        const recordKey = buildKeyRecord(allFields, row)
        const keyStr = buildRecordKeyString(allFields, row)
        const storedEtag = etagMap[keyStr] ?? null
        const etagInfo = resolveEtagForUpdate(allFields, row, tableDataJson, recordKey, storedEtag)
        const recordData = buildInlineUpdateRecord(row)
        const res = await updateRecord(
          selectedTable.ConfigUuid,
          selectedTable.TableName,
          recordKey,
          recordData,
          etagInfo.field || '',
          etagInfo.value || ''
        )
        if (res.success === false) throw new Error(getActionMessage(res) || res.message || 'Failed to update record')
        const msg = getActionMessage(res)
        if (msg && !successMessages.includes(msg)) successMessages.push(msg)
        const code = extractApprovalCode(res)
        if (code && !approvalCodes.includes(code)) approvalCodes.push(code)
      } else if (modifiedRows.length > 1) {
        for (const chunk of chunkRecords(modifiedRows)) {
          const records = chunk.map(row => buildInlineUpdateRecord(row))
          const res = await bulkUpdateRecords(
            selectedTable.ConfigUuid,
            selectedTable.TableName,
            records
          )
          if (res.success === false) throw new Error(getActionMessage(res) || 'Failed to update records')

          const failures = getBulkFailures(res)
          if (failures.length > 0) {
            throw new Error(formatBulkFailureMessage('update', failures))
          }

          const msg = getActionMessage(res)
          if (msg && !successMessages.includes(msg)) successMessages.push(msg)
          const code = extractApprovalCode(res)
          if (code && !approvalCodes.includes(code)) approvalCodes.push(code)
        }
      }

      setIsEditingTable(false)
      setEditedData([])
      releaseTableLockIfHeld()

      if (isYesFlag(selectedTable.ApprovalRequired)) {
        if (successMessages.length > 0) {
          showToast(successMessages.join('\n'))
        } else if (approvalCodes.length > 0) {
          showToast(`Approval request submitted successfully. Document ID: ${approvalCodes.join(', ')}`)
        } else {
          showToast('Approval request submitted successfully.')
        }
      } else {
        showToast(`Saved successfully (${newRows.length} created, ${modifiedRows.length} updated)`)
      }
      await loadTable(selectedTable)
      await onRefreshTableList()
    } catch (e: any) {
      const message = getFriendlyErrorMessage(e)
      showError(message)
    } finally {
      setDataLoading(false)
    }
  }

  /* ============================================================================
   * PHAN 6: THAO TAC XOA BAN GHI VA XU LY LOI KHOA NGOAI FK
   * ============================================================================ */

  function openEditDialog(row: TableRowData) {
    if (!tryStartEditingTable()) return
    setRecordDialogMode('edit')
    setEditingRow(row)
    const recordKey = buildKeyRecord(allFields, row)
    const keyStr = buildRecordKeyString(allFields, row)
    const stored = etagMap[keyStr] ?? null
    setEditSessionEtag(resolveEtagForUpdate(allFields, row, tableDataJson, recordKey, stored))
    setRecordDialogOpen(true)
  }

  function openDeleteDialog(rows: TableRowData | TableRowData[]) {
    if (!tryStartEditingTable()) return
    setDeletingRows(Array.isArray(rows) ? rows : [rows])
    setDeleteDialogOpen(true)
  }

  function handleGo() {
    setAppliedSearchQuery(searchQuery)
    setAppliedFilterValues(filterValues)
  }

  function handleClear() {
    setSearchQuery('')
    setFilterValues({})
    setAppliedSearchQuery('')
    setAppliedFilterValues({})
  }

  async function handleOptimisticLockRefresh() {
    setOptimisticLockOpen(false)
    setRecordDialogOpen(false)
    setEditingRow(null)
    setEditSessionEtag(null)
    if (selectedTable) {
      await loadTable(selectedTable)
      await onRefreshTableList()
    }
  }

  async function fetchRowByKey(
    table: TableConfig,
    recordKey: TableRowData,
    baselineRow: TableRowData | null = null
  ) {
    const targetKeyStr = buildRecordKeyString(allFields, baselineRow || recordKey)
    try {
      const dataResult = await getTableData(table.ConfigUuid, table.TableName)
      const dataJson = dataResult.data_json || ''
      const rows = parseTableDataJson(dataJson, allFields)
      const row =
        rows.find(r => buildRecordKeyString(allFields, r) === targetKeyStr) ||
        data.find(r => buildRecordKeyString(allFields, r) === targetKeyStr) ||
        baselineRow ||
        null
      return { row, dataJson }
    } catch {
      const fallbackRow =
        data.find(r => buildRecordKeyString(allFields, r) === targetKeyStr) ||
        baselineRow ||
        null
      return { row: fallbackRow, dataJson: tableDataJson }
    }
  }

  async function updateRecordWithEtag(
    recordKey: TableRowData,
    fullRecord: TableRowData,
    etagInfo: any
  ) {
    const { field, value, candidates } = etagInfo
    const etagValue = value || candidates?.[0] || ''
    if (!selectedTable) return { success: false, message: 'No table selected' }
    return updateRecord(
      selectedTable.ConfigUuid,
      selectedTable.TableName,
      recordKey,
      fullRecord,
      field || '',
      etagValue
    )
  }

  /* ============================================================================
   * PHAN 7: XU LY XUNG DOT DONG THOI ETAG (OPTIMISTIC CONCURRENCY)
   * ============================================================================ */

  /**
   * Luu ban ghi co co che tu dong hop nhat (Merge) neu ETag bi lech nhe
   * va hien thi OptimisticLockDialog neu phat hien xung dot nghiem trong.
   */
  async function saveEditWithMerge(
    formValues: Record<string, any>,
    dirtyFieldNames: string[],
    retryOnLock = true,
    baselineRow: TableRowData | null = null,
    sessionEtag: any = null
  ): Promise<{ ok: boolean; message?: string }> {
    if (!selectedTable) return { ok: false, message: 'No table selected' }

    const baseline =
      baselineRow ||
      editingRow ||
      data.find(r => {
        const keyA = buildRecordKeyString(allFields, r)
        const keyB = buildRecordKeyString(allFields, formValues)
        return keyA === keyB
      }) ||
      null
    if (!baseline) return { ok: false, message: 'No editing baseline' }

    const recordKey = buildKeyRecord(allFields, baseline)
    const { row: freshRow, dataJson } = await fetchRowByKey(selectedTable, recordKey, baseline)
    if (!freshRow) {
      const message = 'Record not found. It may have been deleted.'
      showError(message)
      return { ok: false, message }
    }

    const { fullRecord, blocked, hasChanges } = mergeRecordForConcurrentEdit(
      allFields,
      baseline,
      freshRow,
      formValues,
      dirtyFieldNames,
      dataJson,
      recordKey
    )

    if (!hasChanges) {
      const message =
        blocked.length > 0
          ? `Cannot save: ${blocked.map(b => b.label).join(', ')} already changed by another user`
          : 'No changes to save'
      showError(message)
      return { ok: false, message }
    }

    const etagForLock =
      sessionEtag ??
      editSessionEtag ??
      etagMap[buildRecordKeyString(allFields, baseline)] ??
      null
    const etagInfo = resolveEtagForUpdate(allFields, baseline, tableDataJson, recordKey, etagForLock)
    const result = await updateRecordWithEtag(recordKey, fullRecord, etagInfo)

    if (result.success === false && retryOnLock && isOptimisticLockError(result.message)) {
      const freshEtag = resolveEtagForUpdate(allFields, freshRow, dataJson, recordKey)
      return saveEditWithMerge(formValues, dirtyFieldNames, false, freshRow, freshEtag)
    }

    if (result.success === false) {
      if (isOptimisticLockError(result.message)) {
        setOptimisticLockOpen(true)
        return { ok: false, message: result.message }
      }
      const message = formatActionErrorMessage(getActionMessage(result) || result.message || 'Update failed')
      showError(message)
      return { ok: false, message }
    }

    setRecordDialogOpen(false)
    setEditSessionEtag(null)
    const approvalCode = extractApprovalCode(result)
    const backendMessage = result.message || result.value?.message || result.data?.message || result.data?.value?.message
    if (isYesFlag(selectedTable.ApprovalRequired)) {
      showToast(backendMessage || `Approval request submitted successfully. Document ID: ${approvalCode || ''}`)
    } else {
      let msg = backendMessage || 'Record updated'
      if (blocked.length > 0) {
        msg += `. Skipped (locked by others): ${blocked.map(b => b.label).join(', ')}`
      }
      showToast(msg)
    }
    await loadTable(selectedTable)
    await onRefreshTableList()
    return { ok: true }
  }

  async function handleSaveRecord(
    formValues: Record<string, any>,
    dirtyFieldNames: string[] = [],
    baselineRow: TableRowData | null = null
  ): Promise<{ ok: boolean; message?: string }> {
    if (!selectedTable) return { ok: false, message: 'No table selected' }
    try {
      if (recordDialogMode === 'create') {
        const recordPayload = buildFullRecordPayload(allFields, formValues, null)
        const result = await createRecord(
          selectedTable.ConfigUuid,
          selectedTable.TableName,
          recordPayload
        )
        if (result.success === false) {
          const message = formatActionErrorMessage(result.message || 'Operation failed')
          showError(message)
          return { ok: false, message }
        }
        setRecordDialogOpen(false)
        const approvalCode = extractApprovalCode(result)
        const backendMessage = result.message || result.value?.message || result.data?.message || result.data?.value?.message
        if (isYesFlag(selectedTable.ApprovalRequired)) {
          showToast(backendMessage || `Approval request submitted successfully. Document ID: ${approvalCode || ''}`)
        } else {
          showToast(backendMessage || 'Record created successfully')
        }
        await loadTable(selectedTable)
        await onRefreshTableList()
        return { ok: true }
      }

      const baseline =
        baselineRow ||
        editingRow ||
        data.find(r => {
          const keyA = buildKeyRecord(allFields, r)
          const keyB = buildKeyRecord(allFields, formValues)
          return JSON.stringify(keyA) === JSON.stringify(keyB)
        }) ||
        null

      const editResult = await saveEditWithMerge(formValues, dirtyFieldNames, true, baseline)
      if (editResult?.ok === false && editResult.message) {
        return { ok: false, message: editResult.message }
      }
      return editResult ?? { ok: true }
    } catch (e: any) {
      const message = getFriendlyErrorMessage(e)
      showError(message)
      return { ok: false, message }
    }
  }

  /**
   * [HAM handleConfirmDelete]: Thuc thi xoa 1 hoac nhieu dong du lieu.
   * Tu dong bat loi Khoa ngoai FK (Foreign Key Reference Error) de hien thi Dialog canh bao chi tiet.
   */
  async function handleConfirmDelete() {
    if (deletingRows.length === 0 || !selectedTable) return
    setDeleteLoading(true)
    try {
      let lastResult: any = null
      if (deletingRows.length === 1) {
        const recordKey = buildKeyRecord(allFields, deletingRows[0])
        lastResult = await deleteRecord(
          selectedTable.ConfigUuid,
          selectedTable.TableName,
          recordKey
        )
        if (lastResult.success === false) {
          setDeleteDialogOpen(false)
          releaseTableLockIfHeld()
          const message = getActionMessage(lastResult)
          if (isFKReferenceError(message)) {
            setFkErrorMessage(parseFKErrorMessage(message))
            setFkErrorOpen(true)
          } else {
            showError(message || 'Delete failed')
          }
          return
        }
      } else {
        const recordKeys = deletingRows.map(row => buildKeyRecord(allFields, row))
        for (const chunk of chunkRecords(recordKeys)) {
          lastResult = await bulkDeleteRecords(
            selectedTable.ConfigUuid,
            selectedTable.TableName,
            chunk
          )
          if (lastResult.success === false) {
            setDeleteDialogOpen(false)
            releaseTableLockIfHeld()
            showError(getActionMessage(lastResult) || 'Delete failed')
            return
          }

          const failures = getBulkFailures(lastResult)
          if (failures.length > 0) {
            setDeleteDialogOpen(false)
            releaseTableLockIfHeld()
            const fkFailure = failures.find(item => isFKReferenceError(item.message))
            if (fkFailure) {
              setFkErrorMessage(parseFKErrorMessage(fkFailure.message))
              setFkErrorOpen(true)
            } else {
              showError(formatBulkFailureMessage('delete', failures))
            }
            await loadTable(selectedTable)
            await onRefreshTableList()
            return
          }
        }
      }
      setDeleteDialogOpen(false)
      const deletedCount = deletingRows.length
      setDeletingRows([])
      const approvalCode = extractApprovalCode(lastResult)
      const backendMessage = getActionMessage(lastResult)
      if (isYesFlag(selectedTable.ApprovalRequired)) {
        showToast(backendMessage || `Approval request submitted successfully. Document ID: ${approvalCode || ''}`)
      } else {
        showToast(backendMessage || `${deletedCount} record${deletedCount > 1 ? 's' : ''} deleted successfully`)
      }
      releaseTableLockIfHeld()
      await loadTable(selectedTable)
      await onRefreshTableList()
    } catch (e: any) {
      showError(getFriendlyErrorMessage(e))
      releaseTableLockIfHeld()
    } finally {
      setDeleteLoading(false)
    }
  }

  // ─── Du lieu loc duoc tinh toan tu filter ──────────────────────────────────
  const filteredData = data.filter(row => {
    const matchesSearch =
      appliedSearchQuery.trim() === '' ||
      Object.values(row).some(v =>
        String(v).toLowerCase().includes(appliedSearchQuery.toLowerCase())
      )

    const matchesKeys = Object.entries(appliedFilterValues).every(([field, val]) => {
      if (!val.trim()) return true
      const cellVal = String(row[field] ?? '')
      return cellVal.toLowerCase().includes(val.toLowerCase())
    })

    return matchesSearch && matchesKeys
  })

  // ─── Tra ve API cong khai cho component UI su dung ────────────────────────
  return {
    // State
    allFields,
    fields,
    data,
    tableDataJson,
    etagMap,
    editSessionEtag,
    setEditSessionEtag,
    dataLoading,
    error,
    setError,
    successMsg,
    setSuccessMsg,
    searchQuery,
    setSearchQuery,
    filterValues,
    setFilterValues,
    appliedSearchQuery,
    appliedFilterValues,
    isEditingTable,
    setIsEditingTable,
    editedData,
    setEditedData,
    inlineErrors,
    recordDialogOpen,
    setRecordDialogOpen,
    recordDialogMode,
    editingRow,
    setEditingRow,
    deleteDialogOpen,
    setDeleteDialogOpen,
    deletingRows,
    setDeletingRows,
    deleteLoading,
    optimisticLockOpen,
    setOptimisticLockOpen,
    fkErrorOpen,
    setFkErrorOpen,
    fkErrorMessage,
    toastOpen,
    setToastOpen,
    toastMessage,
    approvalInfo,
    setApprovalInfo,
    activeTableLock,
    pendingApprovalRecords,
    filteredData,
    // Handlers
    loadTable,
    handleCellChange,
    handleAddRow,
    handleCancelInlineEdits,
    handleRemoveNewRow,
    handleSaveInlineEdits,
    openEditDialog,
    openDeleteDialog,
    handleGo,
    handleClear,
    handleSaveRecord,
    handleConfirmDelete,
    handleOptimisticLockRefresh,
    releaseTableLockIfHeld,
    tryStartEditingTable,
    // Utils
    isFieldReadonly,
    isSystemGeneratedField,
  }
}
