import { useState, useEffect, useRef } from 'react'
import {
  Dialog,
  Bar,
  Button,
  FlexBox,
  Label,
  Text,
  Title,
  Input,
  MessageStrip,
  Icon,
} from '@ui5/webcomponents-react'
import { FieldMeta, TableRowData, AiDescriptionMap } from '../../types'
import { formatCellValue } from '../../utils/displayHelpers'
import { formatHeaderLabel } from '../../utils/tableHelpers'
import { validateMandatory, isAutoGeneratedKeyField } from '../../utils/recordHelpers'
import { validateInlineField } from '../../utils/validationHelpers'
import CellEditControl from '../CellEditControl'

interface RecordDetailsDialogProps {
  open: boolean
  configUuid: string
  tableName: string
  fields: FieldMeta[]
  row: TableRowData | null
  aiDescriptions?: AiDescriptionMap
  permissions?: {
    canCreate?: boolean
    canUpdate?: boolean
    canDelete?: boolean
  }
  disabledActions?: boolean
  onSaveRecord?: (formValues: Record<string, any>, dirtyFieldNames: string[], baselineRow?: TableRowData | null) => Promise<{ ok: boolean; message?: string } | void>
  onDeleteRecord?: (row: TableRowData) => void
  onClose: () => void
}

export default function RecordDetailsDialog({
  open,
  configUuid,
  tableName,
  fields,
  row,
  aiDescriptions = {},
  permissions = { canUpdate: true, canDelete: true },
  disabledActions = false,
  onSaveRecord,
  onDeleteRecord,
  onClose,
}: RecordDetailsDialogProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [editRow, setEditRow] = useState<TableRowData | null>(null)
  const [inlineErrors, setInlineErrors] = useState<Record<number, Record<string, string>>>({})
  const [filterQuery, setFilterQuery] = useState('')
  const [copiedKey, setCopiedKey] = useState<string | null>(null)
  const [copiedAll, setCopiedAll] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState('')

  // Cache fields so if parent reloads table while dialog is open, fields are not lost
  const cachedFieldsRef = useRef(fields)
  if (fields && fields.length > 0) {
    cachedFieldsRef.current = fields
  }
  const effectiveFields = fields && fields.length > 0 ? fields : cachedFieldsRef.current

  // Reset state when opening/closing or row changes
  useEffect(() => {
    if (open && row) {
      setIsEditing(false)
      setEditRow({ ...row })
      setInlineErrors({})
      setSaveError('')
      setFilterQuery('')
    }
  }, [open, row])

  if (!open || !row) return null

  const currentRow = isEditing && editRow ? editRow : row

  // Group fields into Key fields and Regular fields
  const keyFields = effectiveFields.filter(f => f.is_key || f.IsKeyField === 'X')
  const regularFields = effectiveFields.filter(f => !f.is_key && f.IsKeyField !== 'X')

  // Search filter
  const filterText = filterQuery.trim().toLowerCase()
  const filterMatch = (f: FieldMeta) => {
    if (!filterText) return true
    const name = (f.field_name || f.FieldName || '').toLowerCase()
    const label = (f.label || f.LabelText || '').toLowerCase()
    const val = String(currentRow[f.field_name || f.FieldName] ?? '').toLowerCase()
    return name.includes(filterText) || label.includes(filterText) || val.includes(filterText)
  }

  const visibleKeyFields = keyFields.filter(filterMatch)
  const visibleRegularFields = regularFields.filter(filterMatch)

  const handleCopyValue = (fieldKey: string, val: any, e: any) => {
    e?.stopPropagation?.()
    const textToCopy = val != null ? String(val) : ''
    navigator.clipboard.writeText(textToCopy)
    setCopiedKey(fieldKey)
    setTimeout(() => setCopiedKey(null), 2000)
  }

  const handleCopyAllJson = () => {
    const cleanRow = { ...currentRow }
    delete cleanRow._isNew
    delete cleanRow._pendingApproval
    navigator.clipboard.writeText(JSON.stringify(cleanRow, null, 2))
    setCopiedAll(true)
    setTimeout(() => setCopiedAll(false), 2000)
  }

  const handleStartEdit = () => {
    setEditRow({ ...row })
    setInlineErrors({})
    setSaveError('')
    setIsEditing(true)
  }

  const handleCancelEdit = () => {
    setEditRow({ ...row })
    setInlineErrors({})
    setSaveError('')
    setIsEditing(false)
  }

  const handleCellChange = (_rowIndex: number, fieldNameKey: string, newValue: any) => {
    if (!editRow) return
    const updated = { ...editRow, [fieldNameKey]: newValue }
    setEditRow(updated)

    // Validate field on change
    const err = validateInlineField(0, fieldNameKey, newValue, updated, fields, [row], [updated])
    setInlineErrors(prev => {
      const rowErrs = { ...(prev[0] || {}) }
      if (err) {
        rowErrs[fieldNameKey] = err
      } else {
        delete rowErrs[fieldNameKey]
      }
      return { ...prev, 0: rowErrs }
    })
  }

  const handleSave = async () => {
    if (!editRow || !onSaveRecord) return
    setSaveError('')

    // 1. Mandatory field validation
    const missing = validateMandatory(fields.filter(f => !isAutoGeneratedKeyField(f, 'edit')), editRow)
    if (missing.length > 0) {
      const errMap: Record<string, string> = {}
      missing.forEach(name => { errMap[name] = 'Field is required' })
      setInlineErrors({ 0: errMap })
      setSaveError(`Please fill in all required fields: ${missing.join(', ')}`)
      return
    }

    // 2. Check for inline validation errors
    if (inlineErrors[0] && Object.keys(inlineErrors[0]).length > 0) {
      setSaveError('Please fix all field validation errors before saving.')
      return
    }

    // 3. Determine dirty fields
    const dirtyFieldNames = fields
      .map(f => f.field_name || f.FieldName)
      .filter(name => editRow[name] !== row[name])

    if (dirtyFieldNames.length === 0) {
      setIsEditing(false)
      onClose()
      return
    }

    try {
      setSaving(true)
      const res = await onSaveRecord(editRow, dirtyFieldNames, row)
      if (res && res.ok === false) {
        setSaveError(res.message || 'Failed to update record')
        setSaving(false)
        return
      }
      setIsEditing(false)
      setSaving(false)
      onClose()
    } catch (e: any) {
      setSaveError(e?.message || 'Failed to update record')
      setSaving(false)
    }
  }

  return (
    <Dialog
      open={open}
      headerText={isEditing ? `Edit Record — ${tableName}` : `Record Details — ${tableName}`}
      onAfterClose={onClose}
      style={{ width: 'min(92vw, 780px)', maxHeight: '88vh' }}
      footer={
        <Bar
          startContent={
            !isEditing ? (
              <Button
                design="Transparent"
                icon={'copy' as any}
                onClick={handleCopyAllJson}
              >
                {copiedAll ? 'JSON Copied!' : 'Copy Row JSON'}
              </Button>
            ) : null
          }
          endContent={
            <FlexBox gap="8px" alignItems="Center">
              {!isEditing ? (
                <>
                  {onSaveRecord && (
                    <Button
                      design="Default"
                      icon={'edit' as any}
                      disabled={!permissions.canUpdate || disabledActions}
                      onClick={handleStartEdit}
                    >
                      Edit
                    </Button>
                  )}
                  {onDeleteRecord && (
                    <Button
                      design="Negative"
                      icon={'delete' as any}
                      disabled={!permissions.canDelete || disabledActions}
                      onClick={() => onDeleteRecord(row)}
                    >
                      Delete
                    </Button>
                  )}
                  <Button design="Emphasized" onClick={onClose}>
                    Close
                  </Button>
                </>
              ) : (
                <>
                  <Button design="Transparent" onClick={handleCancelEdit} disabled={saving}>
                    Cancel
                  </Button>
                  <Button
                    design="Emphasized"
                    icon={'save' as any}
                    onClick={handleSave}
                    disabled={saving}
                  >
                    {saving ? 'Saving...' : 'Save'}
                  </Button>
                </>
              )}
            </FlexBox>
          }
        />
      }
    >
      <div style={{ padding: '4px 0 16px 0', display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {/* Error message strip if save failed or validation errors exist */}
        {saveError && (
          <MessageStrip design="Negative" onClose={() => setSaveError('')}>
            {saveError}
          </MessageStrip>
        )}

        {/* Quick Search bar if table has multiple fields */}
        {fields.length > 5 && (
          <Input
            placeholder="Search fields or values..."
            value={filterQuery}
            onInput={(e: any) => setFilterQuery(e.target.value)}
            style={{ width: '100%' }}
          />
        )}

        {/* ── Key Fields Group ── */}
        {visibleKeyFields.length > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <FlexBox alignItems="Center" gap="6px">
              <Icon name={'key' as any} style={{ color: '#e09d00', width: '14px', height: '14px' }} />
              <Title level="H6" style={{ color: 'var(--sapTitleColor, #1d2d3e)', margin: 0 }}>
                Primary Key ({visibleKeyFields.length})
              </Title>
            </FlexBox>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
                gap: '10px',
              }}
            >
              {visibleKeyFields.map(f => {
                const name = f.field_name || f.FieldName
                const label = formatHeaderLabel(f)
                const val = currentRow[name]
                const formatted = formatCellValue(f, val)
                const aiDesc = aiDescriptions[name]

                return (
                  <div
                    key={name}
                    style={{
                      background: 'var(--sapWarningBackground, #fffdf2)',
                      border: '1px solid var(--sapCriticalColor, #f0be3d)',
                      borderRadius: '8px',
                      padding: '10px 14px',
                      display: 'flex',
                      flexDirection: 'column',
                      gap: '4px',
                    }}
                  >
                    <FlexBox alignItems="Center" justifyContent="SpaceBetween">
                      <FlexBox alignItems="Center" gap="6px">
                        <Label style={{ fontWeight: 600, color: '#32363a' }}>{label}</Label>
                        <span
                          style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            background: '#ffe699',
                            color: '#73510d',
                            padding: '1px 6px',
                            borderRadius: '4px',
                            fontSize: '0.6875rem',
                            fontWeight: 700,
                            letterSpacing: '0.5px',
                          }}
                        >
                          KEY
                        </span>
                      </FlexBox>
                      {!isEditing && (
                        <Button
                          design="Transparent"
                          icon={'copy' as any}
                          title={copiedKey === name ? 'Copied!' : 'Copy value'}
                          onClick={(e: any) => handleCopyValue(name, val, e)}
                          style={{ height: '24px', minWidth: '24px' }}
                        />
                      )}
                    </FlexBox>
                    <div
                      style={{
                        padding: '6px 8px',
                        background: '#ffffff',
                        borderRadius: '4px',
                        border: '1px solid #e5e5e5',
                        wordBreak: 'break-word',
                        userSelect: 'text',
                        fontWeight: 500,
                      }}
                    >
                      <Text style={{ color: '#1d2d3e', whiteSpace: 'pre-wrap' }}>
                        {formatted || <span style={{ color: '#999', fontStyle: 'italic' }}>&lt;empty&gt;</span>}
                      </Text>
                    </div>
                    {aiDesc?.description && (
                      <Text style={{ fontSize: '0.75rem', color: '#0064d9', marginTop: '2px' }}>
                        💡 {aiDesc.description}
                      </Text>
                    )}
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* ── Regular Fields Group ── */}
        {visibleRegularFields.length > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <Title level="H6" style={{ color: 'var(--sapTitleColor, #1d2d3e)', margin: 0 }}>
              Attributes ({visibleRegularFields.length})
            </Title>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
                gap: '10px',
              }}
            >
              {visibleRegularFields.map(f => {
                const name = f.field_name || f.FieldName
                const label = formatHeaderLabel(f)
                const val = currentRow[name]
                const formatted = formatCellValue(f, val)
                const aiDesc = aiDescriptions[name]
                const isMandatory = f.is_mandatory || f.MandatoryFlag === 'X'

                return (
                  <div
                    key={name}
                    style={{
                      background: isEditing ? '#ffffff' : 'var(--sapGroup_Background, #f9fafb)',
                      border: isEditing ? '1px solid #cbd5e1' : '1px solid var(--sapGroup_BorderColor, #e2e8f0)',
                      borderRadius: '8px',
                      padding: '10px 14px',
                      display: 'flex',
                      flexDirection: 'column',
                      gap: '6px',
                    }}
                  >
                    <FlexBox alignItems="Center" justifyContent="SpaceBetween">
                      <Label style={{ fontWeight: 600, color: '#32363a' }}>
                        {label} {isEditing && isMandatory ? <span style={{ color: '#d32f2f' }}>*</span> : null}
                      </Label>
                      {!isEditing && (
                        <Button
                          design="Transparent"
                          icon={'copy' as any}
                          title={copiedKey === name ? 'Copied!' : 'Copy value'}
                          onClick={(e: any) => handleCopyValue(name, val, e)}
                          style={{ height: '24px', minWidth: '24px' }}
                        />
                      )}
                    </FlexBox>

                    {/* If editing: render CellEditControl. If viewing: render formatted text box */}
                    {isEditing ? (
                      <div style={{ width: '100%', minWidth: 0 }}>
                        <CellEditControl
                          row={currentRow}
                          rowIndex={0}
                          field={f}
                          inlineErrors={inlineErrors}
                          configUuid={configUuid}
                          tableName={tableName}
                          onCellChange={handleCellChange}
                        />
                      </div>
                    ) : (
                      <div
                        style={{
                          padding: '6px 8px',
                          background: '#ffffff',
                          borderRadius: '4px',
                          border: '1px solid #e5e5e5',
                          wordBreak: 'break-word',
                          userSelect: 'text',
                        }}
                      >
                        <Text style={{ color: '#1d2d3e', whiteSpace: 'pre-wrap' }}>
                          {formatted || <span style={{ color: '#999', fontStyle: 'italic' }}>&lt;empty&gt;</span>}
                        </Text>
                      </div>
                    )}

                    {aiDesc?.description && (
                      <Text style={{ fontSize: '0.75rem', color: '#0064d9', marginTop: '2px' }}>
                        💡 {aiDesc.description}
                      </Text>
                    )}
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {visibleKeyFields.length === 0 && visibleRegularFields.length === 0 && (
          <div style={{ padding: '24px', textAlign: 'center' }}>
            <Text style={{ color: '#6a6d70' }}>No fields match "{filterQuery}"</Text>
          </div>
        )}
      </div>
    </Dialog>
  )
}
